export { default as ChatApp } from './src/ChatApp.vue';
export { default as ConversationWorkspaceView } from './src/views/ConversationWorkspaceView.vue';
export { default as DocumentWorkspaceView } from './src/views/DocumentWorkspaceView.vue';
export { default as NormalChatView } from './src/views/NormalChatView.vue';
export { default as CompareChatView } from './src/views/CompareChatView.vue';
export { default as WorkspaceHostApp } from './src/views/WorkspaceHostApp.vue';
export { default as AppTopBar } from './src/components/AppTopBar.vue';
export { default as AttachmentComposer } from './src/components/AttachmentComposer.vue';
export { default as ConversationSidebar } from './src/components/ConversationSidebar.vue';
export { default as AgentPane } from './src/components/AgentPane.vue';
export { default as DocumentEditorPane } from './src/components/DocumentEditorPane.vue';
export { default as DocumentFileTree } from './src/components/DocumentFileTree.vue';
export { default as MessageAnnotationLayer } from './src/components/MessageAnnotationLayer.vue';
export { default as MessageAttachmentStrip } from './src/components/MessageAttachmentStrip.vue';
export { createWorkspaceI18n, translateWorkspaceMessage, useWorkspaceI18n, resolveWorkspaceText, resolveInitialLocale } from './src/i18n';
export { useChatStore } from './src/store/chat';
export { useDocumentWorkspaceStore } from './src/store/documentWorkspace';
export { useCompareStore } from './src/store/compare';
export { CHAT_ROUTES, PRIMARY_WORKSPACE_ROUTES, type ChatRoute, type ChatRoutePath } from './src/routes';
export { openConversationImportDialog, parseConversationImportPayload } from './src/utils/externalFileImport';
