export { default as ChatApp } from './src/ChatApp.vue';
export { default as ConversationWorkspaceView } from './src/views/ConversationWorkspaceView.vue';
export { default as KnowledgeWorkspaceView } from './src/views/KnowledgeWorkspaceView.vue';
export { default as NormalChatView } from './src/views/NormalChatView.vue';
export { default as CompareChatView } from './src/views/CompareChatView.vue';
export { default as AppTopBar } from './src/components/AppTopBar.vue';
export { default as AttachmentComposer } from './src/components/AttachmentComposer.vue';
export { default as ConversationSidebar } from './src/components/ConversationSidebar.vue';
export { default as KnowledgeAssistantPane } from './src/components/KnowledgeAssistantPane.vue';
export { default as KnowledgeEditorPane } from './src/components/KnowledgeEditorPane.vue';
export { default as KnowledgeFileTree } from './src/components/KnowledgeFileTree.vue';
export { default as MessageAnnotationLayer } from './src/components/MessageAnnotationLayer.vue';
export { default as MessageAttachmentStrip } from './src/components/MessageAttachmentStrip.vue';
export { useChatStore } from './src/store/chat';
export { useKnowledgeWorkspaceStore } from './src/store/knowledgeWorkspace';
export { useCompareStore } from './src/store/compare';
export { CHAT_ROUTES, PRIMARY_WORKSPACE_ROUTES, type ChatRoute, type ChatRoutePath } from './src/routes';
export { openConversationImportDialog, parseConversationImportPayload } from './src/utils/externalFileImport';
